CREATE TABLE ZENITSU_CONTATO (
    id INT (11) NOT NULL AUTO_INCREMENT,
    nome VARCHAR (255) DEFAULT NULL,
    email VARCHAR (255) DEFAULT NULL,
    telefone VARCHAR (255) DEFAULT NULL,
    mensagem VARCHAR (800) DEFAULT NULL,
    ip VARCHAR (255) DEFAULT NULL,
    data_hora DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) CHARSET = utf8;

CREATE TABLE ZENITSU_VIEW_HOME (
    id INT (11) NOT NULL AUTO_INCREMENT,
    ip VARCHAR (255) DEFAULT NULL,
    data_hora DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) CHARSET = utf8;


CREATE TABLE ZENITSU_VIEW_DUDEPROJECT (
    id INT (11) NOT NULL AUTO_INCREMENT,
    ip VARCHAR (255) DEFAULT NULL,
    data_hora DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) CHARSET = utf8;